{
 "title": "Proxmox",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(pve_resource_uptime,node)"
    }
   },
   {
    "name": "type",
    "label": "Types",
    "query": {
     "query": "label_values(pve_resource_uptime,type)"
    }
   },
   { "name": "template", "label": "Templates", "query": "No : 0, Yes : 1" }
  ]
 },
 "panels": [
  {
   "title": "Proxmox Resources List",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pve_resource_status{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_resource_cpu{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_resource_disk{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_resource_maxdisk{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_resource_maxcpu{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_resource_maxmem{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_resource_mem{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_resource_uptime{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_resource_disk{node=~\"$node\",type=~\"$type\",template=~\"$template\"} / pve_resource_maxdisk{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_resource_mem{node=~\"$node\",type=~\"$type\",template=~\"$template\"} / pve_resource_maxmem{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxmox Storage List",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "pve_storage_disk{node=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_storage_maxdisk{node=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_storage_status{node=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_storage_disk{node=~\"$node\"} / pve_storage_maxdisk{node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxmox Storage Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_storage_disk{node=~\"$node\"} / pve_storage_maxdisk{node=~\"$node\"}",
     "legendFormat": "{{node}} {{name}}"
    }
   ]
  },
  {
   "title": "Proxmox Resource Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pve_resource_uptime{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pve_resource_status{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_resource_cpu{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Max CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pve_resource_maxcpu{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_resource_disk{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Max Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_resource_maxdisk{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_resource_mem{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Max Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_resource_maxmem{node=~\"$node\",type=~\"$type\",template=~\"$template\"}",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pve_resource_diskread{node=~\"$node\",type=~\"$type\",template=~\"$template\"}[$__rate_interval])",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pve_resource_diskwrite{node=~\"$node\",type=~\"$type\",template=~\"$template\"}[$__rate_interval])",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Net IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pve_resource_netin{node=~\"$node\",type=~\"$type\",template=~\"$template\"}[$__rate_interval])",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  },
  {
   "title": "Proxmox Resource Net OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pve_resource_netout{node=~\"$node\",type=~\"$type\",template=~\"$template\"}[$__rate_interval])",
     "legendFormat": "{{name}} ({{node}}-{{vmid}})"
    }
   ]
  }
 ]
}