name: Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: 'v1.64'
          args: --verbose --timeout=5m

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
